name: Build & Publish to Test PyPi

on:
  push:

jobs:
  build:
    environment: dev
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      - fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests pandas
    - name: Run tests
      run: |
        python -m pytest -v -s
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.1
    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done
      # - name: Upload to Test PyPi Repo
      #   run: |
      #     python -m pip install --upgrade build
      #     python -m pip install setuptools wheel twine
      # - name: Build to Dist
      #   run: |
      #     python -m build
      #   run: |
      #     python -m twine upload -r testpypi dist/*

